// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendAlquimia.Data;

#nullable disable

namespace backendAlquimia.Migrations
{
    [DbContext(typeof(AlquimiaDbContext))]
    [Migration("20250515060500_AjusteDuracionTimeSpan")]
    partial class AjusteDuracionTimeSpan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombinacionNota", b =>
                {
                    b.Property<int>("CombinacionId")
                        .HasColumnType("int");

                    b.Property<int>("NotaSalidaId")
                        .HasColumnType("int");

                    b.HasKey("CombinacionId", "NotaSalidaId");

                    b.HasIndex("NotaSalidaId");

                    b.ToTable("CombinacionNotaSalida", (string)null);
                });

            modelBuilder.Entity("CombinacionNota1", b =>
                {
                    b.Property<int>("Combinacion1Id")
                        .HasColumnType("int");

                    b.Property<int>("NotaCorazonId")
                        .HasColumnType("int");

                    b.HasKey("Combinacion1Id", "NotaCorazonId");

                    b.HasIndex("NotaCorazonId");

                    b.ToTable("CombinacionNotaCorazon", (string)null);
                });

            modelBuilder.Entity("CombinacionNota2", b =>
                {
                    b.Property<int>("Combinacion2Id")
                        .HasColumnType("int");

                    b.Property<int>("NotaFondoId")
                        .HasColumnType("int");

                    b.HasKey("Combinacion2Id", "NotaFondoId");

                    b.HasIndex("NotaFondoId");

                    b.ToTable("CombinacionNotaFondo", (string)null);
                });

            modelBuilder.Entity("Intensidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Intensidades");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PedidoProducto", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("PedidoProducto");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Combinacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Combinaciones");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.CompatibilidadFamiliaOlfativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamiliaOlfativaAId")
                        .HasColumnType("int");

                    b.Property<int>("FamiliaOlfativaBId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaOlfativaBId");

                    b.HasIndex("FamiliaOlfativaAId", "FamiliaOlfativaBId")
                        .IsUnique();

                    b.ToTable("CompatibilidadFamiliasOlfativas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FamiliaOlfativaAId = 1,
                            FamiliaOlfativaBId = 3
                        },
                        new
                        {
                            Id = 2,
                            FamiliaOlfativaAId = 1,
                            FamiliaOlfativaBId = 6
                        },
                        new
                        {
                            Id = 3,
                            FamiliaOlfativaAId = 2,
                            FamiliaOlfativaBId = 3
                        },
                        new
                        {
                            Id = 4,
                            FamiliaOlfativaAId = 3,
                            FamiliaOlfativaBId = 5
                        },
                        new
                        {
                            Id = 5,
                            FamiliaOlfativaAId = 4,
                            FamiliaOlfativaBId = 5
                        },
                        new
                        {
                            Id = 6,
                            FamiliaOlfativaAId = 4,
                            FamiliaOlfativaBId = 9
                        },
                        new
                        {
                            Id = 7,
                            FamiliaOlfativaAId = 8,
                            FamiliaOlfativaBId = 4
                        },
                        new
                        {
                            Id = 8,
                            FamiliaOlfativaAId = 10,
                            FamiliaOlfativaBId = 1
                        });
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.CreacionFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConcentracionAgua")
                        .HasColumnType("float");

                    b.Property<double>("ConcentracionAlcohol")
                        .HasColumnType("float");

                    b.Property<double>("ConcentracionEsencia")
                        .HasColumnType("float");

                    b.Property<int>("CreadorId")
                        .HasColumnType("int");

                    b.Property<int>("IdFormula")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.HasIndex("IdFormula");

                    b.HasIndex("IdPedido");

                    b.ToTable("CreacionesFinales");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.FamiliaOlfativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("FamiliasOlfativas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Notas frescas y chispeantes derivadas de cítricos.",
                            Nombre = "Cítrica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acordes dulces y jugosos de frutas no cítricas.",
                            Nombre = "Frutal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bouquet de flores de tallo, pétalos y capullos.",
                            Nombre = "Floral"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Acordes especiados, resinosos y cálidos.",
                            Nombre = "Oriental"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Esencias de maderas secas, resinosas o ahumadas.",
                            Nombre = "Amaderada"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hierbas y plantas de aroma fresco y limpio.",
                            Nombre = "Aromática"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hojas y tallos recién cortados, sensación herbal.",
                            Nombre = "Verde"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Notas comestibles, dulces y reconfortantes.",
                            Nombre = "Gourmand"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Acordes suaves, limpios y almizclados.",
                            Nombre = "Almizclada"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sensación marina y de brisa fresca y húmeda.",
                            Nombre = "Acuática"
                        });
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CombinacionId")
                        .HasColumnType("int");

                    b.Property<int>("CreadorId")
                        .HasColumnType("int");

                    b.Property<int>("IntensidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CombinacionId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("IntensidadId");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreadorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FamiliaOlfativaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.HasIndex("FamiliaOlfativaId");

                    b.HasIndex("SectorId");

                    b.ToTable("Notas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Cítrico verde, chispeante y ligeramente floral.",
                            FamiliaOlfativaId = 1,
                            Nombre = "Bergamota",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cítrico luminoso y ácido, recuerda a la piel de limón.",
                            FamiliaOlfativaId = 1,
                            Nombre = "Limón",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cítrico dulce y jugoso, con matiz infantil y alegre.",
                            FamiliaOlfativaId = 1,
                            Nombre = "Mandarina",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Frutal crujiente, faceta verde-dulce que aporta frescura.",
                            FamiliaOlfativaId = 2,
                            Nombre = "Manzana",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Fruta roja ácida y azucarada, da un tono juvenil.",
                            FamiliaOlfativaId = 2,
                            Nombre = "Frambuesa",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Floral clásico, aterciopelado y ligeramente especiado.",
                            FamiliaOlfativaId = 3,
                            Nombre = "Rosa",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Floral blanco, opulento, con matiz indólico y sensual.",
                            FamiliaOlfativaId = 3,
                            Nombre = "Jazmín",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Dulce, cremosa y envolvente; aporta calidez oriental.",
                            FamiliaOlfativaId = 4,
                            Nombre = "Vainilla",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Acorde resinoso-balsámico, aporta profundidad y dulzor.",
                            FamiliaOlfativaId = 4,
                            Nombre = "Ámbar",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Madera lactónica, suave y cremosa con faceta almizclada.",
                            FamiliaOlfativaId = 5,
                            Nombre = "Sándalo",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Madera seca, terrosa y ligeramente ahumada.",
                            FamiliaOlfativaId = 5,
                            Nombre = "Cedro",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Aromática herbal, calmante y limpia (toque alcanforado).",
                            FamiliaOlfativaId = 6,
                            Nombre = "Lavanda",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Aromática verde con punto terroso y fresco.",
                            FamiliaOlfativaId = 6,
                            Nombre = "Salvia",
                            SectorId = 2
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Verde lechoso, natural y ligeramente afrutado.",
                            FamiliaOlfativaId = 7,
                            Nombre = "Hoja de Higuera",
                            SectorId = 1
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Cacao profundo, cremoso y envolvente, efecto gourmand.",
                            FamiliaOlfativaId = 8,
                            Nombre = "Chocolate",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Suave, limpio y empolvado; fija y da sensación de piel.",
                            FamiliaOlfativaId = 9,
                            Nombre = "Almizcle Blanco",
                            SectorId = 3
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Acorde ozónico-salado que evoca aire marino fresco.",
                            FamiliaOlfativaId = 10,
                            Nombre = "Brisa Marina",
                            SectorId = 1
                        });
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Opinion");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.PiramideOlfativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Sectores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Notas que se perciben inmediatamente.",
                            Duracion = new TimeSpan(0, 1, 0, 0, 0),
                            Nombre = "Salida"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Notas que definen el carácter del perfume.",
                            Duracion = new TimeSpan(0, 4, 0, 0, 0),
                            Nombre = "Corazón"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Notas de base, las más persistentes.",
                            Duracion = new TimeSpan(0, 8, 0, 0, 0),
                            Nombre = "Fondo"
                        });
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreacionFinalId")
                        .HasColumnType("int");

                    b.Property<int?>("CreadorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("TipoProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreacionFinalId");

                    b.HasIndex("CreadorId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.TipoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposProducto");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Creador", b =>
                {
                    b.HasBaseType("backendAlquimia.Data.Entities.Usuario");

                    b.ToTable("Creadores", (string)null);
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Proveedor", b =>
                {
                    b.HasBaseType("backendAlquimia.Data.Entities.Usuario");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("CombinacionNota", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Combinacion", null)
                        .WithMany()
                        .HasForeignKey("CombinacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Nota", null)
                        .WithMany()
                        .HasForeignKey("NotaSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombinacionNota1", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Combinacion", null)
                        .WithMany()
                        .HasForeignKey("Combinacion1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Nota", null)
                        .WithMany()
                        .HasForeignKey("NotaCorazonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CombinacionNota2", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Combinacion", null)
                        .WithMany()
                        .HasForeignKey("Combinacion2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Nota", null)
                        .WithMany()
                        .HasForeignKey("NotaFondoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PedidoProducto", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.CompatibilidadFamiliaOlfativa", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.FamiliaOlfativa", "FamiliaOlfativaA")
                        .WithMany()
                        .HasForeignKey("FamiliaOlfativaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.FamiliaOlfativa", "FamiliaOlfativaB")
                        .WithMany()
                        .HasForeignKey("FamiliaOlfativaBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamiliaOlfativaA");

                    b.Navigation("FamiliaOlfativaB");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.CreacionFinal", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Creador", "Creador")
                        .WithMany("HistorialDeCreaciones")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Formula", "Formula")
                        .WithMany()
                        .HasForeignKey("IdFormula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");

                    b.Navigation("Formula");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.FamiliaOlfativa", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Creador", null)
                        .WithMany("FamiliasPrefidas")
                        .HasForeignKey("CreadorId");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Formula", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Combinacion", "Combinacion")
                        .WithMany()
                        .HasForeignKey("CombinacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.Creador", "Creador")
                        .WithMany("Formulas")
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Intensidad", "Intensidad")
                        .WithMany()
                        .HasForeignKey("IntensidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combinacion");

                    b.Navigation("Creador");

                    b.Navigation("Intensidad");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Nota", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Creador", null)
                        .WithMany("NotasPreferidas")
                        .HasForeignKey("CreadorId");

                    b.HasOne("backendAlquimia.Data.Entities.FamiliaOlfativa", "FamiliaOlfativa")
                        .WithMany()
                        .HasForeignKey("FamiliaOlfativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.PiramideOlfativa", "Sector")
                        .WithMany("Notas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamiliaOlfativa");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Opinion", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithMany("Opiniones")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Producto", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.CreacionFinal", null)
                        .WithMany("Productos")
                        .HasForeignKey("CreacionFinalId");

                    b.HasOne("backendAlquimia.Data.Entities.Creador", null)
                        .WithMany("CarritoDeCompras")
                        .HasForeignKey("CreadorId");

                    b.HasOne("backendAlquimia.Data.Entities.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendAlquimia.Data.Entities.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Creador", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("backendAlquimia.Data.Entities.Creador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Proveedor", b =>
                {
                    b.HasOne("backendAlquimia.Data.Entities.Usuario", null)
                        .WithOne()
                        .HasForeignKey("backendAlquimia.Data.Entities.Proveedor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.CreacionFinal", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.PiramideOlfativa", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Opiniones");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Creador", b =>
                {
                    b.Navigation("CarritoDeCompras");

                    b.Navigation("FamiliasPrefidas");

                    b.Navigation("Formulas");

                    b.Navigation("HistorialDeCreaciones");

                    b.Navigation("NotasPreferidas");
                });

            modelBuilder.Entity("backendAlquimia.Data.Entities.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
